arb-dir: lib/l10n
template-arb-file: intl_en.arb
output-class: L10n
output-localization-file: l10n.dart
preferred-supported-locales: [en,es]
nullable-getter: false
untranslated-messages-file: untranslated.txt