name: youtube_clone
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  # app_settings: ^5.1.1
  camera: ^0.10.5+5
  flutter:
    sdk: flutter

  connectivity_plus: ^5.0.2
  extended_image: ^8.2.0
  flutter_riverpod: ^2.4.8
  go_router: ^12.1.1
  google_sign_in: ^6.1.6
  grpc: ^3.2.4
  hive: ^4.0.0-dev.2
  image: ^4.1.3
  intl: ^0.18.1
  intl_utils: ^2.8.3
  isar_flutter_libs: ^4.0.0-dev.13
  media_kit: ^1.1.10+1
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  palette_generator: ^0.3.3+3
  path_provider: ^2.1.1
  permission_handler: ^11.3.1
  photo_manager: ^2.8.1
  protobuf: ^3.1.0
  retry: ^3.1.2
  riverpod_annotation: ^2.3.3
  rxdart: ^0.27.7
  sign_in_with_apple: ^5.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  custom_lint: ^0.5.8

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/image/
    - assets/logo/
  fonts:
    - family: YTIcons
      fonts:
        - asset:  assets/fonts/YTIcons.ttf

flutter_intl:
  enabled: true
