name: youtube_clone
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  # app_settings: ^5.1.1
  camera: ^0.11.0+2
  camera_android_camerax: ^0.6.5+5
  camera_platform_interface: ^2.6.0
  connectivity_plus: ^5.0.2
  extended_image: ^8.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.3
  google_sign_in: ^6.2.1
  grpc: ^3.2.4
  hive: ^4.0.0-dev.2
  image: ^4.2.0
  intl: ^0.19.0
  intl_utils: ^2.8.3
  isar_flutter_libs: ^4.0.0-dev.13
  media_kit: ^1.1.10+1
  media_kit_libs_video: ^1.0.4
  media_kit_video: ^1.2.4
  palette_generator: ^0.3.3+3
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  photo_manager: ^3.2.3
  photo_manager_image_provider: ^2.1.1
  protobuf: ^3.1.0
  retry: ^3.1.2
  riverpod_annotation: ^2.3.5
  rxdart: ^0.27.7
  segment_group_list: ^0.0.1
  sign_in_with_apple: ^5.0.0

dependency_overrides:
  win32: ^5.5.3

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/image/
    - assets/logo/
  fonts:
    - family: YTIcons
      fonts:
        - asset:  assets/fonts/YTIcons.ttf
    - family: Roboto
      fonts:
        - asset:  assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
          weight: 200
          style: normal
        - asset: assets/fonts/roboto/Roboto-ThinItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900
          style: normal
        - asset: assets/fonts/roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
    - family: YouTubeSans
      fonts:
        - asset: assets/fonts/YouTubeSansRegular.otf
          weight: 400
          style: normal
        - asset: assets/fonts/YouTubeSansMedium.otf
          weight: 500
          style: normal
        - asset: assets/fonts/YouTubeSansLight.otf
          weight: 300
          style: normal
        - asset: assets/fonts/YouTubeSansBlack.otf
          weight: 900
          style: normal
        - asset: assets/fonts/YouTubeSansBold.otf
          weight: 700
          style: normal
        - asset: assets/fonts/YouTubeSansDarkBlack.otf
          weight: 900
          style: normal
        - asset: assets/fonts/YouTubeSansDarkBold.otf
          weight: 700
          style: normal
        - asset: assets/fonts/YouTubeSansDarkExtraBold.otf
          weight: 800
          style: normal
        - asset: assets/fonts/YouTubeSansDarkLight.otf
          weight: 300
          style: normal
        - asset: assets/fonts/YouTubeSansDarkMedium.otf
          weight: 500
          style: normal
        - asset: assets/fonts/YouTubeSansDarkRegular.otf
          weight: 400
          style: normal
        - asset: assets/fonts/YouTubeSansDarkSemibold.otf
          weight: 600
          style: normal
        - asset: assets/fonts/YouTubeSansExtraBold.otf
          weight: 800
          style: normal
        - asset: assets/fonts/YouTubeSansSemibold.otf
          weight: 600
          style: normal



flutter_intl:
  enabled: true
