/// Flutter icons YTIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  YTIcons
///      fonts:
///       - asset: fonts/YTIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class YTIcons {
  YTIcons._();

  static const _kFontFam = 'YTIcons';
  static const String? _kFontPkg = null;

  static const IconData clip_outlined = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like_outlined = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData watch_later_outlined = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData your_videos_outlined = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history_outlined = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playlists_outlined = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData library_filled = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData library_outlined = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subscriptions_filled = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shorts_filled = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_filled = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_back_outlined = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic_outlined = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData your_channel_outlined = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_vert_outlined = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData podcasts_outlined = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData movies_outlined = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feedbck_outlined = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help_outlined = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData report_outlined = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thanks_outlined = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save_outlined = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData create_outlined = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_up = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_filled = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData live_outlined = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cast_outlined = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_outlined = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fashion_outlined = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_outlined = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData learning_outlined = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_filled = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_playlist_outlined = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up_outlined = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_outlined = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caption_filled = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clip_filled = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dislike_outlined = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_outlined = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_arrow = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData prev = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trending_up_outlined = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unmuted = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_down = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_up_1 = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_circle_outlined = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_forward = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_filled = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_horiz_outlined = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData restart_outlined = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shared_filled = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop_outlined = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shorts_search = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag_fiiled = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData watch_later_filled = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_left = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shorts_comment_filled = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shorts_dislike_filled = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shorts_like_filled = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shorts_share_filled = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reply_outlined = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reply_outlined_1 = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save_outlined_1 = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData description_outlined = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_outlined = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sound_off = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sound_on = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verified_filled = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData closed_caption = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData desktop_expand = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData desktop_minimize = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fullscreen = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_filled_1 = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minimize = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData next = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paid_promotion_outlined = IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData place_outlined = IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dislike_filled = IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google = IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData purchases_membership = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData switch_accounts = IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like_filled = IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube_outlined = IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discover_outlined = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subscriptions_outlined = IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shorts_outlined = IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_outlined = IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_outlined = IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData games_outlined = IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sports_outlined = IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData news_outlined = IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trending_outlined = IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_outlined = IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_outlined = IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_outlined = IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
