/// Flutter icons YTIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  YTIcons
///      fonts:
///       - asset: fonts/YTIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class YTIcons {
  YTIcons._();

  static const _kFontFam = 'YTIcons';
  static const String? _kFontPkg = null;

  static const IconData clip_outlined = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like_outlined = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData watch_later_outlined = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData your_videos_outlined = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history_outlined = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playlists_outlined = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData library_filled = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData library_outlined = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subscriptions_filled = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shorts_filled = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_filled = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_back_outlined = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic_outlined = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData your_channel_outlined = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_vert_outlined = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData podcasts_outlined = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData movies_outlined = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feedbck_outlined = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help_outlined = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData report_outlined = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thanks_outlined = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save_outlined = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData create_outlined = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_filled = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData live_outlined = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cast_outlined = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discover_outlined = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subscriptions_outlined = IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shorts_outlined = IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_outlined = IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_outlined = IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData games_outlined = IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sports_outlined = IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData news_outlined = IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trending_outlined = IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_outlined = IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_outlined = IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_outlined = IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_outlined = IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
