// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxXEMGEgnRDZfyEgzfFAZcSNaqxzyva1E',
    appId: '1:919507162965:web:56f3e7be49625a886581dc',
    messagingSenderId: '919507162965',
    projectId: 'clone-496fa',
    authDomain: 'clone-496fa.firebaseapp.com',
    storageBucket: 'clone-496fa.appspot.com',
    measurementId: 'G-VX22LDWF7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJDFTekYkEfhXz8hpsqBZtRj5xJtQK0R0',
    appId: '1:919507162965:android:80d608131eca37586581dc',
    messagingSenderId: '919507162965',
    projectId: 'clone-496fa',
    storageBucket: 'clone-496fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk6XHHJyKPAAmOVIm7Bk74yqwk9jMX0ww',
    appId: '1:919507162965:ios:d2219c5cc34df37b6581dc',
    messagingSenderId: '919507162965',
    projectId: 'clone-496fa',
    storageBucket: 'clone-496fa.appspot.com',
    iosBundleId: 'com.example.youtubeClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk6XHHJyKPAAmOVIm7Bk74yqwk9jMX0ww',
    appId: '1:919507162965:ios:d2219c5cc34df37b6581dc',
    messagingSenderId: '919507162965',
    projectId: 'clone-496fa',
    storageBucket: 'clone-496fa.appspot.com',
    iosBundleId: 'com.example.youtubeClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxXEMGEgnRDZfyEgzfFAZcSNaqxzyva1E',
    appId: '1:919507162965:web:7e0dcb30eb11f6c96581dc',
    messagingSenderId: '919507162965',
    projectId: 'clone-496fa',
    authDomain: 'clone-496fa.firebaseapp.com',
    storageBucket: 'clone-496fa.appspot.com',
    measurementId: 'G-Q3CVZ37BB3',
  );

}